version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  django:
    build:
      context: ..
      dockerfile: ./docker/local/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ..:/app
    environment:
      - POSTGRES_USER=blemmy
      - USE_DOCKER=yes
    ports:
      - "8000:8000"
    command: /start.sh

  postgres:
    build:
      context: ./postgres/
      dockerfile: ./Dockerfile
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    environment:
      - POSTGRES_USER=blemmy
